name: humset
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=0.2
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.72.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.10.14
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.13.2
  - cfitsio=3.470
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - cryptography=3.1.1
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.10.1
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.1.3
  - flake8=3.7.9
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=3.0.4
  - geographiclib=1.50
  - geopy=2.0.0
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.58.3
  - gmp=6.2.0
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.10
  - imageio=2.6.1
  - importlib-metadata=1.5.0
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jaraco.itertools=5.0.0
  - jasper=1.900.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.1
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - kealib=1.4.13
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgdal=3.0.4
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm8=8.0.1
  - libllvm9=9.0.1
  - libnetcdf=4.7.3
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.17
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.34.0
  - libwebp=1.0.2
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.0.4
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.4
  - ninja=1.10.0
  - nodejs=13.8.0
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numba=0.48.0
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - opencv=4.1.1
  - openh264=1.8.0
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - pandas=1.1.1
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - parso=0.6.1
  - patsy=0.5.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.3
  - proj=6.3.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyzmq=18.1.1
  - qgrid=1.1.1
  - qt=5.12.5
  - qtconsole=4.6.0
  - readline=8.0
  - requests=2.24.0
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=45.1.0
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.0
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.7.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - tzcode=2020a
  - urllib3=1.25.10
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - x264=1!152.20180806
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - affine==2.3.0
    - cftime==1.2.1
    - click==7.1.2
    - click-plugins==1.1.1
    - cligj==0.5.0
    - descartes==1.1.0
    - fiona==1.8.17
    - geopandas==0.8.1
    - motionless==1.3.2
    - munch==2.5.0
    - netcdf4==1.5.4
    - pyperclip==1.8.1
    - pyproj==2.6.1.post1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - rasterio==1.1.7
    - salem==0.3.0
    - shapely==1.7.1
    - snuggs==1.4.7
    - xarray==0.16.1
